### ISSUE TITLE
A better solution to detect images in html

### ISSUE THREAD

**Issue by ksdev-pl** [molteber/puz-autoembed#3]
Hi

> Does anyone have a better solution to detect images in given string?

Maybe Symfony DomCrawler? http://symfony.com/doc/current/components/dom_crawler.html 

Just an idea, I'm not sure if good (the message body does not have to be a html document, how does DomCrawler cope with this? I don't know). 

(Please close this issue.)

Thanks for your work.

**Comment by molteber** [comment]
Thanks for your suggestion. I will look into that :)
